server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location = /products {
        proxy_pass http://product-service.staging.svc.cluster.local:8000/products;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location = /orders {
        proxy_pass http://order-service.staging.svc.cluster.local:8000/orders;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
